### ISSUE TITLE
Does not compile on VS 2012

### ISSUE THREAD

**Issue by micuat** [2bbb/ofxPubSubOsc#1]
https://github.com/2bbb/ofxPubSubOsc/blob/master/src/ofxOscSubscriber.h#L108

```
            return *(sharedInstance ?: sharedInstance = new OscSubscriber);
```

has to be

```
            return *(sharedInstance ? sharedInstance : sharedInstance = new OscSubscriber);
```

**Comment by micuat** [comment]
and in https://github.com/2bbb/ofxPubSubOsc/blob/master/src/ofxOscSubscriber.h#L152

```
        void subscribe(int port, const string &address, typename CallbackParameter::Callback callback) {
```

to

```
        void subscribe(int port, const string &address, CallbackParameter::Callback callback) {
```

**Comment by 2bbb** [comment]
@micuat 
thanks for issue.

`return *(sharedInstance ? sharedInstance : sharedInstance = new OscSubscriber);`
is okay. so, `?:` is only gcc (and follow this).

but, why
`void subscribe(int port, const string &address, typename CallbackParameter::Callback callback)`
is can't callback... nmmmm...
okay, okay, i will follow this. but, nmmm...

**Comment by 2bbb** [comment]
maybe i fixed it.

thanks: @micuat

**Comment by micuat** [comment]
Now it compiles. Thx!

**Comment by 2bbb** [comment]
:+1:
