### ISSUE TITLE
ofParameter::fromString() conversion error for OF0084

### ISSUE THREAD

**Issue by musiko** [2bbb/ofxPubSubOsc#30]
Hi, I got the following error in `ofParameter.h` when testing ofxOscSubscriberExample:

```
template<typename ParameterType>
void ofParameter<ParameterType>::fromString(string str){
	ParameterType v;
	stringstream sstr;
	sstr << str;
	sstr >> v;     //  <-- Error C2679: binary '>>' : no operator found which takes a right-hand operand of type 'ofQuaternion' (or there is no acceptable conversion)
	set(v);
}
```

I am using the latest master branch + VS2012 + Windows7 + OF0084
Would you advise which branch I should use for OF0084 on windows?

**Comment by 2bbb** [comment]
@musiko

hi.

latest master branch doesn't support OF0084.
could you test with [this version](https://github.com/2bbb/ofxPubSubOsc/releases/tag/v0_1_2)

**Comment by musiko** [comment]
Publisher examples worked, but both subscriber examples had the same error...the compilation error occurs whenever `ofxOscSubscriber.h` is included.
Eventually, I commented all ofQuaternion-related codes in the addon to get it compiled. 
Anyway, what a great addon, thanks a lot!

**Comment by 2bbb** [comment]
omg... :sob: 

i don't have same environment now.
could you up the all error messages?

**Comment by musiko** [comment]
The error message is in my first post:

`Error C2679: binary '>>' : no operator found which takes a right-hand operand of type 'ofQuaternion' (or there is no acceptable conversion)`

`ofFromString<ofQuaternion>()` will produce the same error.

**Comment by 2bbb** [comment]
oh... really...?
there are nothing more detailed?

mmm...
not edited ofxOscSubscriberExample has problem?
if you edited that and if making public is good, could you upload the all source code problem occured?

**Comment by 2bbb** [comment]
@musiko 

sorry, i have confirmed in VS2012+oF084+v0.1.2
i will try to fix it!

thanks for good issue!!
:+1:

**Comment by 2bbb** [comment]
@musiko 

maybe i fixed this problem.
please test with [this](https://github.com/2bbb/ofxPubSubOsc/releases/tag/v0_1_3)!!

**Comment by 2bbb** [comment]
so, cause is what `ofQuaternion`'s `operator>>` and `operator<<` is wrong.
i post the PR, but not merged yet... :cry: 
https://github.com/openframeworks/openFrameworks/pull/3976

**Comment by 2bbb** [comment]
(PR is merged!)

**Comment by musiko** [comment]
sorry for the late replay, thank you so much!!

**Comment by 2bbb** [comment]
@musiko 
thanks for good issue!!
