### ISSUE TITLE
std::min compile error on vs 2017

### ISSUE THREAD

**Issue by yumataesu** [2bbb/ofxPubSubOsc#35]
I encontered this error, and had to rewrite some lines.

**Here**
In `ofxOscSubscriberLoadImplementation.h`

1. add `#include <algorithm>`

2. add `min` -> `std::min` on [244](https://github.com/2bbb/ofxPubSubOsc/blob/master/src/details/Subscriber/ofxOscSubscriberLoadImplementation.h#L244) and [251](https://github.com/2bbb/ofxPubSubOsc/blob/master/src/details/Subscriber/ofxOscSubscriberLoadImplementation.h#L251)

---

**my enviroments**
* Widnows 10
* oF 0.10.0
* vs 2017

I didn't create a PR about it because I didn't test on Mac.

thx :)

**Comment by 2bbb** [comment]
@yumataesu 
maybe it is also ok on mac.
please create PR!!

**Comment by yumataesu** [comment]
@2bbb 
Done. https://github.com/2bbb/ofxPubSubOsc/pull/36
