### ISSUE TITLE
Send ofColor through ofxPublishOsc

### ISSUE THREAD

**Issue by igoumeninja** [2bbb/ofxPubSubOsc#38]
Hello my friend, I am trying to send a color: 
`ofxPublishOsc("localhost", 9005, "/color", color);`
defined in header like:
`ofParameter<ofColor> color;`
but I get the error:
![Screenshot from 2019-12-29 18-49-25](https://user-images.githubusercontent.com/155644/71559883-08299980-2a6c-11ea-8097-9773c74eda8f.png)

Any help?
Thanks in advance
Aris

**Comment by 2bbb** [comment]
@igoumeninja 
thanks for reporting bug!

i push the bugfix branch named [dev/fix_publishing_ofParameter](https://github.com/2bbb/ofxPubSubOsc/tree/dev/fix_publishing_ofParameter).
please check it!

**Comment by igoumeninja** [comment]
Now I get this:
![Screenshot from 2019-12-29 20-55-19](https://user-images.githubusercontent.com/155644/71561326-b7bb3780-2a7d-11ea-89dd-03ae476f3bde.png)

**Comment by 2bbb** [comment]
@igoumeninja 
sorry... i got mistaked to commit.
please check it again.

**Comment by igoumeninja** [comment]
It works like a charm! 
Happy New Year!!!

**Comment by 2bbb** [comment]
thanks for checking!
i will merge it to master soon!
happy new year!!
