### ISSUE TITLE
Can I use variables inside ofxSubscribeOsc?

### ISSUE THREAD

**Issue by igoumeninja** [2bbb/ofxPubSubOsc#39]
Hello my friend, 
I would like to ask if it's possible to use my defined variables inside ofxSubscribeOsc, like this way for example:

> ofxSubscribeOsc(9005, "/onset", [](){ ofBackground(bg_color); });

Thanks in advance
Aris

**Comment by 2bbb** [comment]
@igoumeninja 

it is possible. but not correct is what you write.
if you send `/onset [0-255] [0-255] [0-255] ([0-255] is optionally alpha channel)` then you can write:

`ofxSubscribeOsc(9005, "/onset", [](ofColor bg_color) { ofBackground(bg_color); });`

or more simply

`ofxSubscribeOsc(9005, "/onset", ofBackground /* <- this is setter function directly*/);`

please try those!

**Comment by igoumeninja** [comment]
Thanks for answering.
The first one is working the second give me an error:
![Screenshot from 2020-01-17 22-12-16](https://user-images.githubusercontent.com/155644/72643045-7a5c1280-3976-11ea-9319-022f490d324e.png)

One more that I would like to ask is if it's possible to do something like this:
![Screenshot from 2020-01-17 22-16-28](https://user-images.githubusercontent.com/155644/72643294-08d09400-3977-11ea-9c51-9e46fa4adaad.png)

Thanks in advance.

**Comment by 2bbb** [comment]
ah, sorry. `ofBackground` is overloaded function. it isn't able to detect arguments from function name.

and you need to learn C++ lambda (anonymous function). it is not issue about this repository.
maybe, answer what you need is like this:
`[=](ofColor c) { if(condition) { ofBackground(c); });`
https://www.google.com/search?q=lambda+capture+C%2B%2B
let's study!

**Comment by igoumeninja** [comment]
Let's study!!!
Thanks for helping.
