### ISSUE TITLE
[question] how can we log the received messages (subscribed or leaked)?

### ISSUE THREAD

**Issue by moebiussurfing** [2bbb/ofxPubSubOsc#40]
hey @2bbb ,
do you have any snipped of how to do this? is this possible?
I tried following the API doc (for leaked) but I do not understand how to do it...

**Comment by moebiussurfing** [comment]
I am subscribing parameters directly and without any callback:
`ofxSubscribeOsc(OSC_InputPort, address, b);`

Can we maybe have a global callback like when using an ofParameterGroup?

**Comment by 2bbb** [comment]
hi @moebiussurfing 

currently, feature what you say is not implemented.
but it is good idea. i will implement it while COVID-19 shock.

thanks!

**Comment by 2bbb** [comment]
@moebiussurfing 

it was implemented!
https://github.com/2bbb/ofxPubSubOsc/releases/tag/v0_3_1

can use like:

```
#include "ofMain.h"
#include "ofxPubSubOsc.h"

class ofApp : public ofBaseApp {

public:
    inline virtual void setup() override {
        ofxGetOscSubscriber(26666); // create subscriber binding 26666 explicitly
        ofxSubscribeAllOsc([](const ofxOscMessageEx &m,
                              bool is_leaked) {
            ofLogNotice() << m.getWaitingPort() << " : " <<  m.getAddress() << " " << m.getRemoteHost() << " " << m.getRemotePort() << " " << m.getTypeString() << " " << m.getNumArgs();
        });
    }
    inline virtual void update() override {
        std::string random_address = "/";
        for(auto i = 0; i < 4; ++i) {
            random_address += "abcdefghijklmnopqrstuvwxyz"[rand() % 26];
        }
        ofxSendOsc("127.0.0.1", 26666, random_address, rand());
    }
};

int main() {
    ofSetupOpenGL(200, 200, OF_WINDOW);
    ofRunApp(new ofApp());
}
```

**Comment by moebiussurfing** [comment]
thanks @2bbb, I tested on macOS and it works.
 
I subscribed a float and his messages go to the "leak debug" too. (that's the behavior a was looking for)

   ```
 inline virtual void setup() override
    {
        ofSetFrameRate(25);
        ofxGetOscSubscriber(12345); // create subscriber binding 26666 explicitly
        ofxSubscribeAllOsc([](const ofxOscMessageEx &m,
                              bool is_leaked) {
            ofLogNotice()
            << m.getWaitingPort() << " : "
            << m.getAddress() << " "
            << m.getRemoteHost() << " "
            << m.getRemotePort() << " "
            << m.getTypeString() << " "
            << m.getNumArgs();
        });

        ofxSubscribeOsc(12345, "/dimmer/8", dimmer);
    }
```

**Comment by moebiussurfing** [comment]
hey @2bbb ,
do you think this can be implemented to publishers too? 
I mean to allow log all the OSC messages that the addon is sending.

kind of demanding features here, sorry ;-)
forgot about it if you think it's not useful...
thanks again!

**Comment by 2bbb** [comment]
added: https://github.com/2bbb/ofxPubSubOsc/blob/master/src/ofxOscPublisher.h#L761-L769

**Comment by moebiussurfing** [comment]
thankyou @2bbb , you are so kind adding the features I am asking for.

I am trying to add to my code but I am not getting right:
	```.cpp
        ofxGetOscPublisher(OSC_OutputIp_str, OSC_OutputPort); 
	ofxMonitorAllPublishedOsc([&](const ofxOscMessageEx &m,
		bool is_leaked) {
			ofLogNotice()
				<< m.getWaitingPort() << " : "
				<< m.getAddress() << " "
				<< m.getRemoteHost() << " "
				<< m.getRemotePort() << " "
				<< m.getTypeString() << " "
				<< m.getNumArgs();
		});
```

`1>f:\openframeworks\addons\ofxosc_helper\src\ofxosc_helper.cpp(131): error C2664: 'void ofxMonitorAllPublishedOsc(const std::function<void (const ofx::ofxOscMessageEx &,const ofx::PubSubOsc::Publish::Destination &)> &)': cannot convert argument 1 from 'ofxOSC_Helper::setupOSC::<lambda_3300470e7dc3de1b41aae1124712c635>' to 'const std::function<void (const ofx::ofxOscMessageEx &,const ofx::PubSubOsc::Publish::Destination &)> &'`

**Comment by 2bbb** [comment]
@moebiussurfing 
what is leak about sending osc?
can't you find code?
or can't you read code??

ok. I will support you.
https://github.com/2bbb/ofxPubSubOsc/search?q=ofxOscPublisherDestination&unscoped_q=ofxOscPublisherDestination

**Comment by moebiussurfing** [comment]
> or can't you read code??

I am sorry to disturb you, little newbie here, and never used lambda yet, and did not understood the code. Sorry again and thanks

**Comment by 2bbb** [comment]
@moebiussurfing 
don't worry.
you'd better make sure you read the code, i think.

core of this addon is a little complicated, but some part is simple.
for example, `ofxOscPublisherDestination` is simple struct to make code clean.
maybe you can understand.

let's read the codes (what you can read) for now!
