### ISSUE TITLE
it's posible to change the port/ip on runtime?

### ISSUE THREAD

**Issue by moebiussurfing** [2bbb/ofxPubSubOsc#41]
@2bbb 
I ask because, if not, it looks like we need to unsubscribe all with
 'unsubscribe();' 
and then we must subscribe again all the parameters in our 'ofApp'?

Another cool feature could be to mute/bypass all the subscriptions

**Comment by 2bbb** [comment]
no. i don't think what changing port dynamically will be needed much.
but so, i implemented features i had forgotten to implementation is here. (i don't know why those had been implemented...)
maybe it help you?

https://github.com/2bbb/ofxPubSubOsc/blob/master/src/ofxOscSubscriber.h#L596-L602

**Comment by 2bbb** [comment]
@moebiussurfing 
is it helps you? or not?

**Comment by moebiussurfing** [comment]
Yes @2bbb , 
It works well! Thanks a lot. 
I just tested now for it. Sorry for the delay.

I think this is useful because when you add parameters/subscribers on runtime, and you don't want to remember/store what parameters are added to enable/disable one by one manually.

```.cpp
//my callback for bENABLE_Input
	else if (name == "ENABLE INPUT")
	{
		ofxSetOscSubscriberActive(OSC_InputPort, bENABLE_Input);
		bool b = ofxGetOscSubscriberActive(OSC_InputPort);
		cout << "ofxGetOscSubscriberActive: " << b << endl;
	}
```

**Comment by 2bbb** [comment]
@moebiussurfing 
that's good to hear.

so, i know what `enable/disable` is useful. but it was not implemented...
maybe, it was removed when i refactor to C++11...?

**Comment by moebiussurfing** [comment]
do you think there's a similar method but for the publisher?
Something like ofxSetOscPublisherActive instead of ofxSetOscSubscriberActive.
The idea is to allow bypass the sender.

**Comment by 2bbb** [comment]
there is similar feature per address on inner class of publisher.

https://github.com/2bbb/ofxPubSubOsc/blob/1cf001106d2f7f4b9c53e6f38e9c72a5264d7120/src/ofxOscPublisher.h#L246-L253

maybe it can be used like

```cpp
ofxGetOscPublisher("localhost", 22222)->stopPublishTemporary("/hoge");

ofxGetOscPublisher("localhost", 22222)->resumePublish("/hoge");
```

**Comment by moebiussurfing** [comment]
thanks. it's ok. but then we need to store what addresses are we adding to the publisher.
If there's kind of a vector of addresses inside the publisher object, we could bypass all them ...
maybe it's a cool feature if it's easy.

**Comment by 2bbb** [comment]
@moebiussurfing 

that's right!
i implemented it. please check it! (at v0.4.0beta branch)
https://github.com/2bbb/ofxPubSubOsc/commit/87c6c4ffecbaeb8b73e70f2ccd8a9b66d0260605

**Comment by moebiussurfing** [comment]
cool thanks, 
it worked like that:

```.cpp
// Enable / Bypass 
// the Osc out aka publisher:
if (name == bEnableOut.getName()) // bEnableOut changed
{
	auto _addresses = ofxGetPublishedAddresses(IP, PORT);
	ofLogNotice("ofxGetPublishedAddresses") << ofToString(_addresses);

	for (auto& a : _addresses)
	{
		if (bEnableOut.get()) ofxGetOscPublisher(IP, PORT).resumePublish(a);
		else ofxGetOscPublisher(IP, PORT).stopPublishTemporary(a);
	}
}
```

PS:
I don't understand is why the other method is intended for: 
```.cpp
inline std::vector<std::string> ofxGetRegisteredAddresses(const std::string &ip, std::uint16_t port) {
    return ofxGetOscPublisher(ip, port).getRegisteredAddresses();
}
```
Should registered addresses go into the subscriber (instead of the publisher), right?
Why is here on the subscriber?
--

PS:
On that branch, the examples required to modify that:
```
//#include "ofxOscPublisher.h"
#include "ofxPubSubOsc.h" 
```

**Comment by 2bbb** [comment]
@moebiussurfing 
so, publisher has other feature like:
```cpp
int value_for_publish_manually;
void setup() {
  ofxRegisterPublishingOsc(ip, port, an_address, value_for_publish_manually);
}
void update() {
  if(condition) ofxPublishRegisteredOsc(ip, port, an_address); // this send value_for_publish_manually
}
```

**Comment by 2bbb** [comment]
@moebiussurfing 
I enabled github discussion and create new discussion about missing features.
https://github.com/2bbb/ofxPubSubOsc/discussions/46
