### ISSUE TITLE
Weird behavior for ofxSubscribeOsc

### ISSUE THREAD

**Issue by sadmb** [2bbb/ofxPubSubOsc#48]
I couldn't find specific reason yet but sometimes it doesn't receive OSC from older apps which open before receiver app.
It happens when sending to 127.0.0.1 and the receiver app (using ofxSubscribeOsc) doesn't have any OSC sender function.
To solve this, simply adding ofxSendOsc on setup so it starts to receive OSC from older app.

But I couldn't reproduce small example with this issue.

**Comment by 2bbb** [comment]
hi @sadmb 

thanks for posting issue.
what envs do you use?

if you use windows, please try to remove ofxSendOsc and put `sleep(few_seconds)` to top of main function.

**Comment by 2bbb** [comment]
if needed, please reopen.

thanks.
